packages: []

catalog:
  '@antfu/utils': latest
  '@nuxt/eslint': 1.5.2
  '@nuxt/icon': 1.15.0
  '@nuxtjs/color-mode': 3.5.2
  '@shikijs/markdown-it': ^3.7.0
  '@shikijs/monaco': ^3.3.0
  '@types/markdown-it': ^14.1.2
  '@unocss/nuxt': 66.3.3
  '@vueuse/nuxt': 13.5.0
  markdown-it: ^14.1.0
  markdown-it-async: ^2.2.0
  monaco-editor: ^0.52.2
  monaco-themes: ^0.4.5
  monaco-vim: ^0.4.2
  nuxt: ^3.17.6
  shiki: ^3.3.0
  splitpanes: ^4.0.3

catalogs:
  build:
    unocss: ^66.2.0
  dev:
    '@antfu/eslint-config': ^4.14.1
    '@types/node': ^22.15.31
    '@unocss/eslint-plugin': ^66.2.0
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.0
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    vitest: ^3.2.3
    vue-tsc: ^2.2.10
  frontend:
    vue: ^3.5.16
    vue-router: ^4.5.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
